<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework><AssemblyName>ESD.Data</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ESD.Core\ESD.Core.csproj" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>
</Project>
